blog/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    
   # 雑記ブログ関連
    #path('',views.IndexView.as_view(),name='blog_index'),
    #path(r'tech/',views.IndexView.as_view(),name='tech_index'),
#    path(r'anime/',views.IndexView.as_view(),name='anime_index'),
    path(r'tech/<int:blog_id>/',views.tech_detail,name='tech_detail'),
    path(r'anime/<int:blog_id>/',views.anime_detail,name='anime_detail'),
    ]

django_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from .sitemaps import (
    StaticViewSitemap,
    AnimeSitemap,
   
)
from .feeds import (
    LatestFeed,
)

sitemaps = {
    'static': StaticViewSitemap,
    'anime': AnimeSitemap,
}

urlpatterns = [

    path('adbum/', admin.site.urls),

    path('sentiment/anime/feed/', LatestFeed()),
    path('mecab/',include('mecab.urls')),
    path('blog/',include('blog.urls')),
    path('', include('sentiment.urls')),

    path('sitemap3.xml', sitemap, {'sitemaps': sitemaps}, name='sitemap3'),

    path('robots.txt', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    # 手動の場合
    #path('sitemap_del.xml', TemplateView.as_view(template_name='sitemap_del.xml', content_type='application/xml')),
    #path('sitemap2.xml', sitemap, {'sitemaps': sitemaps2}, name='sitemap2'),
    path('ads.txt', TemplateView.as_view(template_name='ads.txt', content_type='text/plain')),
    path('feed/', LatestFeed()),
]

mecab/urls.py
# -*- coding: utf-8 -*-

from django.urls import path
from . import views

app_name = 'mecab'

urlpatterns = [
    
   # mecab関連
    path(r'gen-katsuyo/',views.addword,name='addword'),
    path(r'addwiki/',views.addwiki,name='addwiki'),
    ]

mecab/models.py
from django.db import models

# Create your models here.

mecab/views.py
from django.shortcuts import render
from .dictadd import dictadd
import csv

# Create your views here.

def addwiki(request):
    
    return render(request,'mecab/addwiki.html')


def addword(request):
    #print('mecab')
    if request.method == "GET":
        params = {
                 'base':None,
                 'w_class':None,
                 'result':None,

                 }
    else:
        w_class = request.POST.get('group_link_radios')
        base = request.POST.get('base')
        yomi = request.POST.get('yomi')
        hitei = request.POST.get('hitei')

        if w_class == '形容詞':
            #print('形容詞')
            with open("/opt/mecab-ipadic-neologd/build/mecab-ipadic-2.7.0-20070801-neologd-20200910/Adj.csv", "r", encoding="utf_8", newline="") as f:
                reader = csv.reader(f)
                dic_l = [r for r in reader]
                #print('len:',len(dic_l))
                #print(dic_l[0])
        elif w_class == '動詞':
            #print('動詞')
            with open("/opt/mecab-ipadic-neologd/build/mecab-ipadic-2.7.0-20070801-neologd-20200910/Verb.csv", "r", encoding="utf_8", newline="") as f:
                reader = csv.reader(f)
                dic_l = [r for r in reader]   
                #print('len:',len(dic_l))

        
        result = dictadd(w_class,base,hitei,yomi,dic_l)
        #print('result:',result)
        params = {
            'base':base,
            'w_class':w_class,
            'result':result,
            }
       
    #print('param',params)
    return render(request,'mecab/addword.html',params)

mecab/templates/mecab/addword.html
{% load static %}
{% load filter %}
{% load social_share %}
<!DOCTYPE html>
<html lang="ja">
<head prefix="og:http://ogp.me/ns#">
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-NGPST6PSGS"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-NGPST6PSGS');
    </script>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, user-scalable=yes">
    <title>MeCabユーザー辞書用コスト生成ツール | 動詞・形容詞 | ぷらこめ</title>
    <link rel="canonical" href="https://purakome.net/mecab/gen-katsuyo/">
    <meta name="description" content="MeCabのユーザー辞書作成用　動詞・形容詞の活用と生起コストを自動で生成するツール。">
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:site" content="@LeiLingVei"/>
    <meta name="twitter:domain" content="purakome.net"/>
    <meta name="twitter:title" content="MeCabユーザー辞書用コスト生成ツール | 動詞・形容詞 | ぷらこめ"/>
    <meta name="twitter:description" content="MeCabのユーザー辞書作成用　動詞・形容詞の活用と生起コストを自動で生成するツール。"/>
    {% with filename="image/header_forblogger.webp" %}
    <meta name="twitter:image" content="{% static filename %}"/>
    {% endwith %}



<!-- Font Awesome -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.css"
  rel="stylesheet"
/>
    <!-- custam css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

</head>


<body>


<div class="d-flex justify-content-center align-items-center vh-100 bg-white">
  <div class="spinner-border text-info" role="status" id="loading">
    <span class="visually-hidden">エントリ作成中です...</span>
  </div>
  <span class="text-info nowloading">&nbsp;エントリ作成中です..</span>
</div>

<div id="hide_contents">


<div class="container" style="margin-top:3rem;margin-bottom:15rem;">

    <div style="display:inline;">
        <a class="title" role="button" href="https://purakome.net">
          <img src="{% static 'image/siteicon_anime.webp' %}" height="90" width="230" alt="サイトアイコン">
        </a>
        <h1 class="fs-1 fw-bold text-center mt-2">MeCabユーザー辞書用<br>活用・生起コスト自動生成ツール | 動詞 形容詞</h1>
    </div>


    <p class="fs-3 text-center mt-5 mb-5">登録したい単語の活用と生起コストを自動で生成します。<br>単語の原形、読み仮名、否定形(動詞のみ)を入力してください。</p>

    <form action="{% url 'mecab:addword' %}" method="post">
        {% csrf_token %}
        <div style="margin:auto;width:300px;">
            <div class="fs-4 d-flex justify-content-center mb-4">
                <div class="form-check">
                  <input class="form-check-input" style="margin-left:1rem;" type="radio" id="verb" name="group_link_radios" value="動詞" checked/>
                  <label class="form-check-label" for="verb">
                  動詞
                   </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" style="margin-left:1rem;" type="radio" id="adj" name="group_link_radios" value="形容詞"/>
                  <label class="form-check-label" for="adj">
                  形容詞
                   </label>
                </div>
            </div>
            <div class="form-outline mb-4">
              <input type="text" required="required" style="height:40px;" name="base" id="form2" class="form-control" />
              <label class="form-label" for="form2">原形を入力</label>
            </div>
            <div class="form-outline mb-4">
              <input type="text" required="required" style="height:40px;" name="yomi" id="form3" class="form-control" />
              <label class="form-label" for="form3">読み仮名(ひらがな)を入力</label>
            </div>
            <div class="form-outline mb-4">
              <input type="text" style="height:40px;" name="hitei" id="form4" class="form-control" />
              <label class="form-label" for="form4">【動詞のみ】否定形(～ず)を入力</label>
            </div>

            <button type="submit" class="btn btn-primary btn-block mb-4 fs-5">エントリを作成する</button>
        </div>
    </form>


    <p class="fs-5 text-center mt-4 mb-6">例）バズる → 【原形】バズる、【読み仮名】ばずる、【否定形】バズらず</p>


    {% if result != None %}
    <hr>
    <div class="mb-6">
        {% if result == 0 %}
        <p class="fs-3 text-warning text-center"><span class="fw-bold">{{base}}({{w_class}})</span>:エントリはシステム辞書に既に存在しています</p>
        {% elif result == 1 %}
        <p class="fs-3 text-warning text-center"><span class="fw-bold">{{base}}({{w_class}})</span>:登録不可(動詞ではありません)</p>
        {% elif result == 2 %}
        <p class="fs-3 text-warning text-center"><span class="fw-bold">{{base}}({{w_class}})</span>:登録不可(形容詞ではありません)</p>
        {% elif result == 3 %}
        <p class="fs-3 text-warning text-center"><span class="fw-bold">{{base}}({{w_class}})</span>:登録不可(形容詞・イイ or 形容詞・不変化型)</p>
        {% elif result == 4 %}
        <p class="fs-3 text-warning text-center"><span class="fw-bold">{{base}}({{w_class}})</span>:否定形を正しく入力してください</p>
        {% else %}
        <div class="table-responsive">
            <table class="table fw-bold fs-5">
                <thead class="table-light">
                    <tr>
                    <th>表層形</th>
                    <th>左文脈ID</th>
                    <th>右文脈ID</th>
                    <th>生起コスト</th>
                    <th>品詞</th>
                    <th>品詞細分類1</th>
                    <th>品詞細分類2</th>
                    <th>品詞細分類3</th>
                    <th>活用型</th>
                    <th>活用形</th>
                    <th>原形</th>
                    <th>読み</th>
                    <th>発音</th>
                    </tr>
                </thead>
                <tbody>
                    {% for r in result %}
                    <tr>
                    <td>{{r.表層形}}</td>
                    <td>{{r.左文脈ID}}</td>
                    <td>{{r.右文脈ID}}</td>
                    <td>{{r.生起コスト}}</td>
                    <td>{{r.品詞}}</td>
                    <td>{{r.品詞細分類1}}</td>
                    <td>{{r.品詞細分類2}}</td>
                    <td>{{r.品詞細分類3}}</td>
                    <td>{{r.活用型}}</td>
                    <td>{{r.活用形}}</td>
                    <td>{{r.原形}}</td>
                    <td>{{r.読み}}</td>
                    <td>{{r.発音}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endif %}
    </div>

    {% endif %}
            

    <!--share button-->
    <div class="fs-4 text-center mt-5">
        <p>共有する</p>
        <div style="display: inline-block; "><i class='fab fa-twitter-square fa-lg'></i></div>
        <div style="display: inline-block; "><i class='fab fa-facebook-square fa-lg'></i></div>
        <div style="display: inline-block; "><i class='fab fa-twitter-square fa-lg'></i></div>
        <div style="display: inline-block; "><i class='fab fa-facebook-square fa-lg'></i></div>

    <!--share button -->
    </div>





    
    <!--注意事項-->
    <div style="max-width:60rem;line-height:3rem;margin: auto;background:floralwhite; border:black; margin-top:4rem; margin-bottom:3rem;">
        <p class="fs-4 text-center">【注意事項】</p>
        <ul>
        <li class="fs-5 text-left">生起コストはデフォルトのシステム辞書に存在する類似単語から引用します</li>
        </ul>
    </div>

<!-- container -->
</div>





<div id="page_top">
  <a href="#"></a>
</div>

<!--Footer-->
<footer class="py-5 bg-black">
    <div class="container">
        <p class="m-0 text-center text-white small">Copyright &copy; ぷらこめ 2022</p>
        <hr>
        <a href="{% url 'contact' %}" style="text-decoration:none; color:black;">
          <p class="m-0 text-center text-white">お問い合わせ</p>
        </a>
        <hr>
        <a href="{% url 'sitepolicy' %}" style="text-decoration:none; color:black;">
          <p class="m-0 text-center text-white">サイトポリシー</p>
        </a>
        <hr>
        <a href="{% url 'aboutus' %}" style="text-decoration:none; color:black;">
          <p class="m-0 text-center text-white">About us</p>
        </a>
        <br>
        <br>

    </div>

</footer>

<!-- hide_contents -->
</div>

<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.1.0/mdb.min.js"
></script>

<script>

var loading = document.getElementById('loading');
var contents = document.getElementById('hide_contents');

window.addEventListener("pageshow", () => {
  if( loading.parentNode.classList.contains('vh-100') == true ){
     console.log("readed!");
     loading.classList.add('d-none');
     loading.parentNode.classList.replace('vh-100', 'd-none');
     contents.classList.remove('d-none');

  }
});



window.addEventListener("beforeunload", () => {

    console.log("moving..");

      loading.classList.remove('d-none');
      loading.parentNode.classList.replace('d-none', 'vh-100');
      contents.classList.add('d-none');

});

</script>

</body>
</html>